### ISSUE TITLE
"ERROR 'NoneType' object is not iterable" on failed transaction

### ISSUE THREAD

**Issue by brianmaissy** [laixintao/iredis#333] opened 2020-05-13 11:12 UTC
When a transaction fails, iredis doesn't properly handle the result of the EXEC command (null reply)
```
localhost:6379> watch foo
OK
localhost:6379> multi
OK
localhost:6379> get bar                                          <transaction>
QUEUED
localhost:6379> exec                                             <transaction>
(error) ERROR 'NoneType' object is not iterable
```

Contents of the log:
```
 INFO [Command] exec
 INFO [Prepare command] Redis: exec, Shell: None
 INFO [Split command] command: exec, args: []
DEBUG [After hook] Command is exec, unset transaction.
 INFO [Redis-Server] Response: None
 INFO [render] Find callback render_list, for command: exec
ERROR 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/brian/.local/pipx/venvs/iredis/lib/python3.6/site-packages/iredis/client.py", line 304, in send_command
    yield self.render_response(redis_resp, command_name)
  File "/home/brian/.local/pipx/venvs/iredis/lib/python3.6/site-packages/iredis/client.py", line 199, in render_response
    rendered = callback(response)
  File "/home/brian/.local/pipx/venvs/iredis/lib/python3.6/site-packages/iredis/renders.py", line 125, in render_list
    for item in text:
TypeError: 'NoneType' object is not iterable
 INFO Print result prompt_toolkit.formatted_text.base.FormattedText: FormattedText([('class:type', '(error) '), ('class:error', "ERROR 'NoneType' object is not iterable")])
```

environment details:

- iredis version 1.6.2
- python 3.6.9
- ubuntu 18.04
- redis version 4.0.9

**Comment by laixintao** [comment] 2020-05-16 15:49
Hi @brianmaissy Thanks for reporting!

But I can reproduce this bug in my environment:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/9675939/82124127-a033df80-97cf-11ea-8635-dd1c85378611.png">

My log said the server's response for `EXEC` is `[None]` instead of your `None`.

```
 INFO [Redis-Server] Response: [None]
```

Can you show me your `pip list`? Maybe because you use a different version of redis-py than mine. Mine is `redis               3.4.1`

**Comment by brianmaissy** [comment] 2020-05-16 20:33
Sorry if it wasn't clear from my description, but you need to make the EXEC fail. Immediately before the EXEC, from another connection, run: `set foo bar`

**Comment by laixintao** [comment] 2020-05-18 14:20
Thanks, yes the `exec` may return `nil` when `watch` ed value changed, said the redis-doc: https://redis.io/commands/exec#return-value

Fixed in next release, please upgrade :) ❤️

**Comment by brianmaissy** [comment] 2020-05-18 14:29
thanks!

**Closed** 2020-05-18 14:34 UTC

**Comment by laixintao** [comment] 2020-05-18 14:36
Code in master fixed this issue, but my current work for redis6 support https://github.com/laixintao/iredis/issues/328 blocks the release. So you have to wait if you want to use the latest version which included the patch.

But you can install from master if this fix is urgent for you :) master is also stable enough
