### ISSUE TITLE
password contains @

### ISSUE THREAD

**Issue by Meaningisuse** [laixintao/iredis#487] opened 2024-02-01 07:26 UTC
<img width="927" alt="image" src="https://github.com/laixintao/iredis/assets/15310195/10b68970-7f01-4690-bfd8-8c6c3ab3ec07">
<img width="203" alt="image" src="https://github.com/laixintao/iredis/assets/15310195/c573092d-1524-40a2-bc22-b1b6a696414d">

**Comment by laixintao** [comment] 2024-02-02 14:43
Ha! never thought about that case! thanks, will fix later.

**Comment by laixintao** [comment] 2024-02-06 08:20
Hi @Meaningisuse after checking from the code, I found it should handle the case that password containing `@`, maybe the `@` is not the issue? can see https://github.com/laixintao/iredis/pull/488/files , I add a test case and it passed.

can you give me a full alias_dsn line that can reproduce your issue? so I can reproduce then fix it. (please don't give me your real password, can fake one or change some characters of the domain and password of this one)

thanks.

**Comment by Meaningisuse** [comment] 2024-02-06 09:24
> Hi @Meaningisuse after checking from the code, I found it should handle the case that password containing `@`, maybe the `@` is not the issue? can see https://github.com/laixintao/iredis/pull/488/files , I add a test case and it passed.
> 
> can you give me a full alias_dsn line that can reproduce your issue? so I can reproduce then fix it. (please don't give me your real password, can fake one or change some characters of the domain and password of this one)
> 
> thanks.

[alias_dsn]
test=redis://030b5bdf-7b61-4101-a7a8-a891b9beba65@Hr1FJTRi7bDLcPQa@audit.test.com:30265/2

**Comment by laixintao** [comment] 2024-02-07 06:29
Oh I saw the issue now: the `:` can not be eliminated:

If you only have password, write like this:

```
test=redis://:030b5bdf-7b61-4101-a7a8-a891b9beba65@Hr1FJTRi7bDLcPQa@audit.test.com:30265/2
```

without `:` the url parser is confused, it would think the whole line is a domain.

https://github.com/laixintao/iredis/blob/master/iredis/data/iredisrc#L83

**Comment by laixintao** [comment] 2024-02-15 10:31
Hi @Meaningisuse I am going to close this issue as this is not a bug, feel free to reopen if you still have issues ;D

**Closed by laixintao** 2024-02-15 10:31 UTC
